[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = [
    "node_modules/@liamcottle/push-receiver/src/gcm/checkin.proto",
    "node_modules/@liamcottle/push-receiver/src/gcm/android_checkin.proto"
  ]